CREATE SCHEMA IF NOT EXISTS bike_tracker AUTHORIZATION bike_tracker;

ALTER SCHEMA bike_tracker OWNER TO bike_tracker;

ALTER DEFAULT PRIVILEGES IN SCHEMA bike_tracker GRANT ALL PRIVILEGES ON TABLES TO bike_tracker;

ALTER DEFAULT PRIVILEGES IN SCHEMA bike_tracker GRANT USAGE ON SEQUENCES TO bike_tracker;
